// import reporter from 'cucumber-html-reporter';

// const options = {
//   theme: 'bootstrap', // You can choose other themes like 'simple', 'foundation', etc.
//   jsonFile: './reports/cucumber-report.json',
//   output: './reports/cucumber-report.html',
//   reportSuiteAsScenarios: true,
//   launchReport: true,
// };

// reporter.generate(options);

import reporter from 'cucumber-html-reporter';
import fs from 'fs';

// Path to the JSON report generated by Cucumber
const jsonFilePath = './reports/cucumber-report.json';

console.log(`Checking if the JSON file exists at: ${jsonFilePath}`);

// Check if the JSON report file exists and is not empty
if (fs.existsSync(jsonFilePath) && fs.statSync(jsonFilePath).size > 0) {
  console.log('JSON report found. Generating HTML report...');

  const options = {
    theme: 'bootstrap',             // Theme for the HTML report
    jsonFile: jsonFilePath,        // Path to the JSON report
    output: './reports/cucumber-report.html',  // Output location for the HTML report
    reportSuiteAsScenarios: true,  // Shows each scenario as a separate suite
    launchReport: true             // Automatically open the HTML report in the browser
  };

  // Generate the HTML report
  reporter.generate(options);
} else {
  console.error('Cucumber JSON report is empty or not generated. Please check the test run.');
}
